# Copyright (c) 2021 Intel Corporation.

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.config.pythonpublisher.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.config.pythonpublisher.publish_port }}
    name: publisher-port
  - port: {{ .Values.config.pythonpublisher.server_port }}
    name: server-port
  selector:
    app: pythonpublisher
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pythonpublisher
  name: deployment-python-publisher
  namespace: {{ .Values.namespace }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonpublisher
  template:
    metadata:
      labels:
        app: pythonpublisher
    spec:
      {{- if and .Values.DOCKER_USERNAME .Values.DOCKER_PASSWORD }}
      imagePullSecrets:
      - name: registryauth
      {{- end }}
      containers:
      - name: ia-python-publisher
        image: {{ .Values.DOCKER_REGISTRY }}ia_python_publisher:{{ .Values.EII_VERSION }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        securityContext:
          privileged: true
        volumeMounts:
        {{- if eq .Values.config.pythonpublisher.IPC true}}
        - name: {{ .Values.volumes.eii_socket.name }}
          mountPath: {{ .Values.volumes.eii_socket.location }}
        {{- end }}
        {{ if eq .Values.env.DEV_MODE false}}
        - name: etcd-certs
          mountPath: /run/secrets/etcd/
        {{ end }}

        env:
        - name: AppName
          value: "PythonPublisher"
        - name: DEV_MODE
          value: '{{ .Values.env.DEV_MODE }}'
        - name: ETCD_HOST
          value: {{ .Values.config.etcd.name }}
        - name: ETCD_CLIENT_PORT
          value: '{{ .Values.config.etcd.client_port }}'
        - name:  ETCD_PREFIX
          value: ''
        {{- if eq .Values.config.pythonpublisher.IPC false}}
        - name: PUBLISHER_Image_Metadata_TYPE
          value: "zmq_tcp"
        - name: PUBLISHER_Image_Metadata_ENDPOINT
          value: "0.0.0.0:{{ .Values.config.pythonpublisher.publish_port }}"
        - name: SERVER_echo_service_TYPE
          value: "zmq_tcp"
        - name: SERVER_echo_service_ENDPOINT
          value: "0.0.0.0:{{ .Values.config.pythonpublisher.server_port }}"
        {{- else }}
        - name: PUBLISHER_Image_Metadata_TYPE
          value: "zmq_ipc"
        - name: PUBLISHER_Image_Metadata_ENDPOINT
          value: "{{ .Values.env.SOCKET_DIR }}"
        - name: SERVER_echo_service_TYPE
          value: "zmq_ipc"
        - name: SERVER_echo_service_ENDPOINT
          value: "{{ .Values.env.SOCKET_DIR }}"
        {{- end }}
        {{ if eq .Values.env.DEV_MODE false}}
        - name: CONFIGMGR_CACERT
          value: "/run/secrets/etcd/ca_certificate.pem"
        - name: CONFIGMGR_CERT
          value: "/run/secrets/etcd/PythonPublisher_client_certificate.pem"
        - name: CONFIGMGR_KEY
          value: "/run/secrets/etcd/PythonPublisher_client_key.pem"
        {{ end }}

      volumes:
      {{- if eq .Values.config.pythonpublisher.IPC true}}
      - name: {{ .Values.volumes.eii_socket.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.volumes.eii_socket.name }}
      {{- end }}
      {{ if eq .Values.env.DEV_MODE false}}
      - name: etcd-certs
        secret:
          secretName: eii-certs
          items:
          - key: ca_certificate.pem
            path: ca_certificate.pem
          - key: PythonPublisher_client_certificate.pem
            path: PythonPublisher_client_certificate.pem
          - key: PythonPublisher_client_key.pem
            path: PythonPublisher_client_key.pem
      {{ end }}
