---
file:
  version: "1.0.0"
  author: "Intel"
  date: "Sun Sep 1 13:34:13 PDT 2019"
  description: "Data for Demo IOUnit data points"
datapoints:
- id: "D1"
  attributes:
    type: "HOLDING_REGISTER"
    addr: 1
    width: 1
    datatype: "INT16"
  polling:
    pollinterval: 1000
    realtime: false

- id: "D2"
  attributes:
    type: "HOLDING_REGISTER"
    addr: 2
    width: 1
    datatype: "INT16"
  polling:
    pollinterval: 1000
    realtime: false

- id: "D3"
  attributes:
    type: "HOLDING_REGISTER"
    addr: 3
    width: 1
    datatype: "INT16"    
  polling:
    pollinterval: 1000
    realtime: false

- id: "D4"
  attributes:
    type: "HOLDING_REGISTER"
    addr: 4
    width: 1
    datatype: "INT16"
  polling:
    pollinterval: 1000
    realtime: false

    
- id: "D5"
  attributes:
    type: "HOLDING_REGISTER"
    addr: 5
    width: 1
    datatype: "INT16"
  polling:
    pollinterval: 1000
    realtime: false

- id: "D6"
  attributes:
    type: "HOLDING_REGISTER"
    addr: 6
    width: 1
    datatype: "INT16"
  polling:
    pollinterval: 1000
    realtime: false

- id: "D7"
  attributes:
    type: "HOLDING_REGISTER"
    addr: 7
    width: 1
    datatype: "INT16"
  polling:
    pollinterval: 1000
    realtime: false

- id: "D8"
  attributes:
    type: "HOLDING_REGISTER"
    addr: 8
    width: 1
    datatype: "INT16"
  polling:
    pollinterval: 1000
    realtime: false

- id: "D9"
  attributes:
    type: "HOLDING_REGISTER"
    addr: 9
    width: 1
    datatype: "INT16"
  polling:
    pollinterval: 1000
    realtime: false

- id: "D10"
  attributes:
    type: "COIL"
    addr: 10
    width: 1
    datatype: "INT16"
  polling:
    pollinterval: 1000
    realtime: false

- id: "D11"
  attributes:
    type: "HOLDING_REGISTER"
    addr: 11
    width: 1
    datatype: "INT16"
  polling:
    pollinterval: 1000
    realtime: false

- id: "D12"
  attributes:
    type: "HOLDING_REGISTER"
    addr: 12
    width: 1
    datatype: "INT16"
  polling:
    pollinterval: 1000
    realtime: false

- id: "D13"
  attributes:
    type: "HOLDING_REGISTER"
    addr: 13
    width: 1
    datatype: "INT16"
  polling:
    pollinterval: 1000
    realtime: false

- id: "D14"
  attributes:
    type: "HOLDING_REGISTER"
    addr: 14
    width: 1
    datatype: "INT16"
  polling:
    pollinterval: 1000
    realtime: false

- id: "D15"
  attributes:
    type: "HOLDING_REGISTER"
    addr: 15
    width: 1
    datatype: "INT16"
  polling:
    pollinterval: 1000
    realtime: false

- id: "D16"
  attributes:
    type: "HOLDING_REGISTER"
    addr: 16
    width: 1
    datatype: "INT16"
  polling:
    pollinterval: 1000
    realtime: false

- id: "D17"
  attributes:
    type: "HOLDING_REGISTER"
    addr: 17
    width: 1
    datatype: "INT16"
  polling:
    pollinterval: 250
    realtime: true

- id: "D18"
  attributes:
    type: "HOLDING_REGISTER"
    addr: 18
    width: 1
    datatype: "INT16"
  polling:
    pollinterval: 250
    realtime: true

- id: "D19"
  attributes:
    type: "HOLDING_REGISTER"
    addr: 19
    width: 1
    datatype: "INT16"
  polling:
    pollinterval: 250
    realtime: true

- id: "D20"
  attributes:
    type: "HOLDING_REGISTER"
    addr: 20
    width: 1
    datatype: "INT16"
  polling:
    pollinterval: 250
    realtime: true

- id: "D21"
  attributes:
    type: "HOLDING_REGISTER"
    addr: 21
    width: 1
    datatype: "INT16"
  polling:
    pollinterval: 250
    realtime: true

- id: "D22"
  attributes:
    type: "HOLDING_REGISTER"
    addr: 22
    width: 1
    datatype: "INT16"
  polling:
    pollinterval: 250
    realtime: true

- id: "D23"
  attributes:
    type: "HOLDING_REGISTER"
    addr: 23
    width: 1
    datatype: "INT16"
  polling:
    pollinterval: 250
    realtime: true

- id: "D24"
  attributes:
    type: "HOLDING_REGISTER"
    addr: 24
    width: 1
    datatype: "INT16"
  polling:
    pollinterval: 250
    realtime: true
    
- id: "D25"
  attributes:
    type: "HOLDING_REGISTER"
    addr: 25
    width: 1
  polling:
    pollinterval: 0
    realtime: true

- id: "D26"
  attributes:
    type: "HOLDING_REGISTER"
    addr: 26
    width: 1
  polling:
    pollinterval: 0
    realtime: true

- id: "D27"
  attributes:
    type: "HOLDING_REGISTER"
    addr: 27
    width: 1
  polling:
    pollinterval: 0
    realtime: true

- id: "D28"
  attributes:
    type: "HOLDING_REGISTER"
    addr: 28
    width: 1
  polling:
    pollinterval: 0
    realtime: true    
